name: build

on: [push]

jobs:
  build-pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get tex packages
        run: sudo apt-get install -y texlive texlive-xetex texlive-bibtex-extra biber texlive-lang-czechslovak latexmk texlive-extra-utils
      
      - name: Build
        run: |
          cd ${{ github.workspace }}
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: ${{ github.workspace }}/out/ctufit-thesis.pdf
          retention-days: 5
